### ISSUE TITLE
Javascript -> Typescript로 변환해보면 어떨까요?

### ISSUE THREAD

**Issue by jeonghyeon-net** [Resten1497/soldier_badge#1]
Typescript가 가독성, 유지보수 등 Javascript에 비해 좋은 점이 많다고 생각합니다.

이번에 한번 바꿔보면 어떨까요?

**Comment by jeonghyeon-net** [comment]
[Pull Request](https://github.com/Resten1497/soldier_badge/pull/3) 요청드렸습니다.

**Comment by resten1497** [comment]
확인했습니다, 
사실 제가 TS 쪽은 잘몰라서 JS로 진행한거였는데,
그렇게 큰 프로젝트는 아니니 TS로 해도 큰 문제는 없을것같네요

PR 승인했습니다
