### ISSUE TITLE
다른 Badge들과 다른 디자인

### ISSUE THREAD

**Issue by jeonghyeon-net** [Resten1497/soldier_badge#4]
img.shields.io 에서 제공해주는 Badge 하고 비교했을때,  
생김새가 좀 달라서 한 줄에 이어서 사용하면 디자인 적으로 예쁘지 않은 것 같아요.

[![Pull Request](https://img.shields.io/github/issues-pr/Resten1497/soldier_badge)](https://github.com/Resten1497/soldier_badge/pulls)

![soldierDate](http://goonba.xyz/?endDate=20211218)

디자인을 맞춰보면 어떨까 싶어요.

**Comment by resten1497** [comment]
원래 shields.io 디자인에서 착안해서 만든거긴한데,
일단 조금더 맞춰보겠습니다.

원래 계획은 R.O.K.A 뿐만 아니라   
공군(R.O.K.A.F) 이나 해병대 등도 추가 하려 했었어요

**Comment by jeonghyeon-net** [comment]
정말 Issue를 닫으시는건가요..?

@Resten1497

**Comment by resten1497** [comment]
재오픈했습니다, 생각해보니 이건 계속 유지해야할것같네요

**Comment by resten1497** [comment]
![Badage](https://img.shields.io/badge/R.O.K.A-D--1000-green)

이런식으로 보여주면될까요?

**Comment by jeonghyeon-net** [comment]
네! 녹색이 너무 밝은 것만 제외하면, 아주 좋습니다.

**Comment by resten1497** [comment]
위 이미지가 shield.io에서 직접 값 지정해서 추가한건데,
기존처럼 굳이 svg로 만들 필요는 없을것같네요..

다만, 전역 일을  parameter로 받아서 img로 뿌려주는거는 필요할 것 같으니 
이 기능은 오늘 한번 테스트해보겠습니다.

shield에서 이런 기능을 지원할줄은 몰랐네요 ;;

**Comment by resten1497** [comment]
![badage](https://img.shields.io/badge/R.O.K.A-D--1000-%23097a27)

색은 이정도로면 좋을것같은데 글꼴은 못바꾸나 싶은..ㅠㅠ

**Comment by jeonghyeon-net** [comment]
오 색 잘 뽑으셨네요 Good Good

저는 글꼴 예뻐보여요

**Comment by resten1497** [comment]
변경했습니다 확인부탁드려요!

shields 이용해서 디자인 통일했습니다.

**Comment by jeonghyeon-net** [comment]
확인했습니다!
꽤 멋집니다.

**Comment by resten1497** [comment]
이번에 변경된거는 shields 라이브러리를사용하는데, Readme에 추가해주면될까요??

**Comment by jeonghyeon-net** [comment]
네 README.me에 기재 후  
이슈 닫아주시면 됩니다!

수고하셨습니다!

**Comment by resten1497** [comment]
Dependency 란에 shield.io를 명시헀습니다.

이 이슈는 닫도록 하겠습니다
수고하셨습니다.

**Comment by resten1497** [comment]
큰 문제 없으면 이버전으로 1.0.0 올리려하는데 괜찮으신가요??

**Comment by jeonghyeon-net** [comment]
넵넵넵
