### ISSUE TITLE
색

### ISSUE THREAD

**Issue by jeonghyeon-net** [Resten1497/soldier_badge#7]
* 전역이 얼마 남지 않았거나 (빨간색)
* 전역했거나 (회색)
* 복무 시작 전이거나 (노란색)

색을 커스터마이징 하거나 해줬으면 좋을 것 같아요

**Comment by resten1497** [comment]
현재는 군 별로 색을 분류하고있는데,
살짝 애매하네요.

#6 이랑 같이 연계해서 고려해보는게 좋을것같아요

![img](https://img.shields.io/badge/%EC%82%B0%EC%97%85%EA%B8%B0%EB%8A%A5%EC%9A%94%EC%9B%90-%20%EA%B5%AC%EC%A7%81%EC%A4%91-%097a27)
이라던지?

**Comment by resten1497** [comment]
아니면 임의로 텍스트 지정하게 하는 것도 방법일것같긴해요,
Shield.io 에서 색도 임의로 결정할 수 있으니까요

**Comment by jeonghyeon-net** [comment]
좋은 아이디어 입니다

저희가 템플릿을 미리 만들어 두는 것도 좋을 것 같아요.

README.md 처럼 개별 문서로 템플릿 목록을 알려주면 어떨까요?

**Comment by resten1497** [comment]
연휴동안 생각을 좀 해보았습니다.

위 말씀하신것처럼 하려면 url을 바꿔야 할것같다는 생각이 우선들었어요
예를들면,

```markdown
http://goonba.xyz/custom/?type="산업기능요원"&status="구직중"&color=HEX
```
이런식으로 정적인 데이터들은 이런식으로 URL  구조를 짤 수 있을것같은데,
위 말씀하신 것처럼, 날짜 별로 색을 구별하게 되면, 아예 새롭게 구조를 짜야할것같은데
이건 parameter를 어떻게 받아야할지 모르겠네요.. 혹시 의견있으신가요?

현재 하고있는방식인, endDate만 받아와서,  D-Day의 Count 별로 색을 바꾸는 방법도 있는데,
이러면 기존의 방식과 큰 차이가 없을것같아서요..

**Comment by jeonghyeon-net** [comment]
일단 크게 가지말고

"endDate만 받아와서, D-Day의 Count 별로 색을 바꾸는 방법"

만 해보면 어떨까요

커스터마이징은 제가 봤을때 너무 큰 일이 되는 것 같습니다.

**Comment by resten1497** [comment]
그러면 군종별로 분류하는걸 이름만 바꾸는게 좋을까요?
지금은 군종별로 색만 바꾸는거로 했으니까요..

- 전역이 얼마 남지 않았거나 (빨간색)
- 전역했거나 (회색)
- **-복무 시작 전이거나 (노란색)**
-
복무시작전은 좀 고려를 해봐야할것같아요..
endDate만으로는 고려할 수 없을것같으니까요...

**Comment by jeonghyeon-net** [comment]
1. 네. 일단 이름만 먼저 제공해주고
추후에 필요성이 느껴지면 추가하면 좋을 것 같아요.

2. 복무 시작 전은 제공을 안해줘도 좋을 것 같네요 ㅋㅋ 제가 너무 오바해서 생각한 것 같아요.
이 뱃지가 필요한 사람은 이미 시작한 사람들 뿐일테니..
