### ISSUE TITLE
알림 서비스 개발 제안

### ISSUE THREAD

**Issue by jeonghyeon-net** [Resten1497/soldier_badge#9]
## 내용

서비스에 변경점이 생겼을때, 사용자들에게 일괄적으로 알림을 보내주면 좋을 것 같아요 (예: 이메일)

## 계기

깃허브 프로필에 들어가봤는데 soldier badge가 엑박으로 표시되어서 이상해가지고 레포 들어와보니 도메인이 변경된 사실을 알 수 있었네요

제가 깃허브 프로필을 신경쓰지 않았다면 계속 엑박으로 표시되는 불편함을 겪었을 것 같습니다..

**Comment by resten1497** [comment]
최근에 도메인이 만료된걸 알아서, 다시 도메인 구매했고,
한 1~2일 뒤면 원래 도메인으로 사용가능합니다.

알림을 주고는 싶은데, 이게 기본적으로 readme.md에 한줄로 추가하는거라 크게 떠오르는 방법이 없네요 ㅠㅠ

**Comment by jeonghyeon-net** [comment]
음~~ 그냥 깃허브 워칭하고 있었으면 해결되는 문제였네용

제가 너무 오버해서 생각했던 것 같습니당

**Comment by resten1497** [comment]
ㅎㅎ 넵
아 그리고 도메인 연장했으니 전 도메인으로 계속 쓰셔도 될것같아요!

**Comment by jeonghyeon-net** [comment]
앗 이미 헤로쿠 주소로 변경했어요 ㅋㅋ

리드미에 주소 두개 다 적어주심 어떨까여

**Comment by resten1497** [comment]
좋습니다!
